server:
  port: 9300
spring:
  datasource:
    url:  jdbc:mysql://49.233.66.244:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username:  root
    password:  113066
    driver-class-name:  com.mysql.jdbc.Driver
    #dubbo配置
    #dubbo中的服务名称
  dubbo:
    application:  user-web
    protocol:
        #dubbo的通信协议名称
      name:  dubbo
    registry:
        #zookeeper注册中心地址
      address:  zookeeper://49.235.153.158:2181?backup=49.235.153.158:2183,49.235.153.158:2182
      protocol:  zookeeper
    base-package: com.mqkmall
mybatis:
  mapperLocations:  classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case:  true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root:  info
