
server:
  port: 9100
spring:
  datasource:
    url:  jdbc:mysql://49.233.66.244:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username:  root
    password:  113066
    driver-class-name:  com.mysql.jdbc.Driver
mybatis:
  mapperLocations:  classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case:  true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root:  debug